export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    

    GET_CATEGORIES: "GET_CATEGORIES",
    POST_CATEGORIES: "POST_CATEGORIES",
    PUT_CATEGORIES: "PUT_CATEGORIES",
    DELETE_CATEGORIES: "DELETE_CATEGORIES",
    SELECTED_CATEGORY: "SELECTED_CATEGORY",
    REMOVE_SELECTED_CATEGORY: "REMOVE_SELECTED_CATEGORY",


    GET_ROLES: "GET_ROLES",
    POST_ROLES: "POST_ROLES",
    PUT_ROLES: "PUT_ROLES",
    DELETE_ROLES: "DELETE_ROLES",
    SELECTED_ROLES: "SELECTED_ROLES",
    REMOVE_SELECTED_ROLES: "REMOVE_SELECTED_ROLES",


    GET_CUSTOMERS: "GET_CUSTOMERS",
    // POST_CUSTOMERS: "POST_CUSTOMERS",
    PUT_CUSTOMERS: "PUT_CUSTOMER",
    DELETE_CUSTOMERS: "DELETE_CUSTOMER",
    SELECTED_CUSTOMERS: "SELECTED_CUSTOMER",
    REMOVE_SELECTED_CUSTOMERS: "REMOVE_SELECTED_CUSTOMERS",


    GET_ORDERS: "GET_ORDERS",
    PUT_ORDERS: "PUT_ORDERS",
    DELETE_ORDERS: "DELETE_ORDERS",
    SELECTED_ORDERS: "SELECTED_ORDERS",
    REMOVE_SELECTED_ORDERS: "REMOVE_SELECTED_ORDERS",



  };
  